"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { motion,useReducedMotion } from "framer-motion";
import { productService } from "@/services/productService";
import { Product } from "@/types";

export default function PromoCarousel(){
 const [promos,setPromos]=useState<Product[]>([]); const [loading,setLoading]=useState(true); const reduce=useReducedMotion();
 useEffect(()=>{(async()=>{const {data}=await productService.getPromotions();setPromos(data||[]);setLoading(false)})()},[]);
 if(loading)return <div className="w-full bg-slate-50/50 pb-4 pt-6"><div className="mx-auto max-w-7xl px-4"><div className="mb-4 h-6 w-32 animate-pulse rounded-lg bg-slate-200"/><div className="flex gap-4 overflow-hidden">{[0,1,2].map(i=><div key={i} className="h-[160px] w-[280px] flex-none animate-pulse rounded-2xl bg-slate-200 sm:w-[340px]"/>)}</div></div></div>;
 if(!promos.length)return null;
 const render=(promo:Product,index:number)=>{const parts=promo.discount_badge?promo.discount_badge.split(" "):["% off"];const href=promo.category_slug?`/produtos/categoria/${promo.category_slug}`:"/#catalogo";return <motion.div key={`${promo.id}-${index}`} whileHover={reduce?undefined:{y:-5,scale:1.01}} transition={{type:"spring",stiffness:320,damping:26}} className="h-[160px] w-[280px] flex-none sm:h-[180px] sm:w-[340px] md:h-[200px] md:w-[400px]"><Link href={href} className="group relative flex h-full w-full overflow-hidden rounded-2xl border border-slate-100/60 bg-[#f4f8f0] shadow-sm transition-shadow duration-300 hover:shadow-xl md:rounded-[2rem]"><div className="relative flex h-full w-[40%] items-center justify-center overflow-hidden bg-[#b2e633]/10 sm:w-[45%]"><div className="absolute -left-20 -top-20 h-48 w-48 rounded-full bg-[#b2e633] opacity-90 sm:h-64 sm:w-64"/>{promo.image_url?<Image src={promo.image_url} alt={promo.name} fill sizes="160px" className="-rotate-6 object-contain p-3 mix-blend-multiply transition-transform duration-500 group-hover:rotate-0 group-hover:scale-[1.04]"/>:<span className="text-[10px] text-slate-400">Sem imagem</span>}</div><div className="z-10 flex w-[60%] flex-col items-start justify-center px-3 sm:w-[55%] sm:px-4"><span className="text-[10px] font-medium italic text-[#0e4d32] sm:text-sm">Oferta Especial</span><h3 className="my-0.5 line-clamp-2 text-xs font-black uppercase leading-tight text-[#0e4d32] sm:text-base">{promo.name}</h3><p className="mt-1 text-[10px] font-semibold text-slate-500 sm:text-xs">Com até</p><div className="flex items-baseline"><span className="text-2xl font-black tracking-tighter text-[#0e4d32] sm:text-3xl">{parts[0]}</span>{parts[1]&&<span className="ml-1 text-xs font-bold text-[#0e4d32] sm:text-sm">{parts[1]}</span>}</div></div></Link></motion.div>};
 const auto=promos.length>2&&!reduce;
 return <motion.section initial={{opacity:0,y:reduce?0:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:reduce?.01:.6}} className="w-full overflow-hidden bg-slate-50/50 pb-4 pt-6"><div className="mx-auto mb-3 max-w-7xl px-4 sm:mb-4"><h2 className="text-xl font-bold tracking-tight text-slate-900 sm:text-2xl">As melhores ofertas</h2></div><div className="w-full overflow-hidden [mask-image:linear-gradient(to_right,transparent_0,black_8%,black_92%,transparent_100%)]">{auto?<div className="animate-infinite-scroll flex w-max py-2 hover:[animation-play-state:paused]"><div className="flex shrink-0 gap-3 pr-3 sm:gap-4 sm:pr-4">{promos.map(render)}</div><div aria-hidden="true" className="flex shrink-0 gap-3 pr-3 sm:gap-4 sm:pr-4">{promos.map((p,i)=>render(p,i+promos.length))}</div></div>:<div className="flex gap-3 overflow-x-auto px-4 py-2 sm:gap-4 sm:px-8">{promos.map(render)}</div>}</div></motion.section>
}
